name: Deploy Resume to EC2

on:
  push:
    branches:
      - main  # Triggers on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up SSH
      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v1
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      # Step 3: Verify SSH Connection
      - name: Verify SSH Connection
        run: |
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'echo "SSH connection successful"'

      # Step 4: Deploy index.html to EC2
      - name: Deploy index.html via SCP
        run: |
          scp -v -o StrictHostKeyChecking=no ./path/to/local/index.html ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/index.html
